---
title: "Analysis"
---

```{=html}
<iframe height="800" width="90%" frameborder="no" src="https://tayyibahshah.shinyapps.io/scatter/"> </iframe>
```
This analysis delves into the trends of alcohol-specific deaths across genders and examines the impact of the COVID-19 pandemic on these statistics. The data highlights significant disparities between male and female death rates, as well as notable increases in mortality rates over the years.

Consistent with previous years, the data reveals a stark gender gap in alcohol-specific mortality rates. In 2022, the rate of alcohol-specific deaths for males remained approximately double that of females. This persistent gap underscores the need for targeted interventions and support systems tailored to address gender-specific challenges related to alcohol consumption and its consequences.

Comparing with 2019, there have been statistically significant increases in the alcohol-specific death rate across regions, notably in England, Wales, and Scotland. The data shows that in 2022, the number of alcohol-specific deaths registered was 4.2% higher than in 2021 and a substantial 32.8% higher than in 2019, the last pre-COVID-19 pandemic year. Furthermore, the total number of deaths recorded in 2022 reached 10,048, marking the highest number on record.

The observed increase in alcohol-specific deaths aligns with the timeline of the COVID-19 pandemic, suggesting a potential correlation between the two phenomena. The pandemic likely played a significant role in exacerbating mental health challenges, leading to increased alcohol consumption and related fatalities. Factors such as social isolation, unemployment, financial strain, and loss of loved ones may have contributed to this uptick in alcohol-related mortality.
